admin_vg_postnord_create_booking:
  path: vg_postnord/create_booking
  methods: [POST]
  defaults:
    _controller: 'Vilkas\Postnord\Controller\Admin\VgPostnordBookingController::createBookingAction'

admin_vg_postnord_bulk_generate_label:
  path: vg_postnord/bulk_generate_booking
  methods: [POST]
  defaults:
    _controller: 'Vilkas\Postnord\Controller\Admin\VgPostnordBookingController::bulkGenerateLabelAction'

admin_vg_postnord_ajax_generate_label:
  path: vg_postnord/ajax_generate_label
  methods: [POST]
  defaults:
    _controller: 'Vilkas\Postnord\Controller\Admin\VgPostnordBookingController::ajaxGenerateLabelAction'

admin_vg_postnord_index_action:
  path: vg_postnord/index_action
  methods: [GET]
  defaults:
    _controller: 'Vilkas\Postnord\Controller\Admin\VgPostnordBookingController::indexAction'