services:
  _defaults:
    public: true

  vilkas.postnord.repository.vgpostnordcartdata:
    class: 'Vilkas\Postnord\Repository\VgPostnordCartDataRepository'
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - Vilkas\Postnord\Entity\VgPostnordCartData

  vilkas.postnord.repository.vgpostnordbooking:
    class: 'Vilkas\Postnord\Repository\VgPostnordBookingRepository'
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - Vilkas\Postnord\Entity\VgPostnordBooking

  vilkas.postnord.service.vgpostnordbookingservice:
    class: 'Vilkas\Postnord\Service\VgPostnordBookingService'
    arguments:
      - '@doctrine.orm.default_entity_manager'
      - '@translator'
      - '@prestashop.adapter.legacy.context'

 # define the grid definition factory
  vilkas.postnord.grid.definition.factory.vg_postnord_booking_grid_definition_factory:
    class: 'Vilkas\Postnord\Grid\Definition\Factory\VgPostnordBookingGridDefinitionFactory'
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
    public: true

 # define the grid query builder
  vilkas.postnord.grid.query.vg_postnord_booking_query_builder:
    class: 'Vilkas\Postnord\Grid\Query\Builder\VgPostnordBooking'
    parent: 'prestashop.core.grid.abstract_query_builder'
    public: true
    arguments:
        - '@prestashop.core.query.doctrine_search_criteria_applicator'

  # define the grid data factory
  vilkas.postnord.grid.vg_postnord_booking_data_factory:
    class: 'PrestaShop\PrestaShop\Core\Grid\Data\Factory\DoctrineGridDataFactory'
    arguments:
      - '@vilkas.postnord.grid.query.vg_postnord_booking_query_builder' # service id of our query builder
      - '@prestashop.core.hook.dispatcher' # every doctrine query builder needs the hook dispatcher
      - '@prestashop.core.grid.query.doctrine_query_parser' # parser to get the raw SQL query
      - 'vgpostnordbooking' # this should match grid id

  # define the grid factory
  vilkas.postnord.grid.vg_postnord_booking_grid_factory:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    arguments:
      - '@vilkas.postnord.grid.definition.factory.vg_postnord_booking_grid_definition_factory' # our definition factory
      - '@vilkas.postnord.grid.vg_postnord_booking_data_factory'              # our data factory
      - '@prestashop.core.grid.filter.form_factory'                            # core service needed by grid factory
      - '@prestashop.core.hook.dispatcher'                                     # core service needed by grid factory

  vilkas.postnord.form.identifiable_object.data_provider.vg_postnord_booking_form_data_provider:
    class: 'Vilkas\Postnord\Form\VgPostnordBookingFormDataProvider'
    arguments:
      - '@vilkas.postnord.repository.vgpostnordbooking'

  vilkas.postnord.form.type.vg_postnord_booking_type:
    class: 'Vilkas\Postnord\Form\VgPostnordBookingType'
    parent: 'form.type.translatable.aware'
    public: true
    arguments:
        - '@=service("prestashop.adapter.multistore_feature").isUsed()'
    tags:
        - { name: form.type }

  vilkas.postnord.form.type.vg_postnord_parcel_type:
    class: 'Vilkas\Postnord\Form\VgPostnordParcelType'
    parent: 'form.type.translatable.aware'
    public: true
    arguments:
      - '@=service("prestashop.adapter.multistore_feature").isUsed()'
    tags:
      - { name: form.type }

  vilkas.postnord.form.type.vg_postnord_customs_declaration_type:
    class: 'Vilkas\Postnord\Form\VgPostnordCustomsDeclarationType'
    parent: 'form.type.translatable.aware'
    public: true
    arguments:
      - '@=service("prestashop.adapter.multistore_feature").isUsed()'
    tags:
      - { name: form.type }

  vilkas.postnord.form.type.vg_postnord_detailed_description_type:
    class: 'Vilkas\Postnord\Form\VgPostnordDetailedDescriptionType'
    parent: 'form.type.translatable.aware'
    public: true
    arguments:
      - '@=service("prestashop.adapter.multistore_feature").isUsed()'
    tags:
      - { name: form.type }

  vilkas.postnord.form.identifiable_object.builder.vg_postnord_booking_form_builder:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Builder\FormBuilder'
    factory: 'prestashop.core.form.builder.form_builder_factory:create'
    arguments:
      - 'Vilkas\Postnord\Form\VgPostnordBookingType'
      - '@vilkas.postnord.form.identifiable_object.data_provider.vg_postnord_booking_form_data_provider'

  vilkas.postnord.form.identifiable_object.data_handler.vg_postnord_booking_form_data_handler:
    class: 'Vilkas\Postnord\Form\VgPostnordBookingFormDataHandler'
    arguments:
      - '@vilkas.postnord.repository.vgpostnordbooking'
      - '@doctrine.orm.default_entity_manager'

  vilkas.postnord.form.identifiable_object.handler.vg_postnord_booking_form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
    factory: 'prestashop.core.form.identifiable_object.handler.form_handler_factory:create'
    arguments:
      - '@vilkas.postnord.form.identifiable_object.data_handler.vg_postnord_booking_form_data_handler'
